#!/bin/sh

PROJECT_ROOT=$(git rev-parse --show-toplevel)

# Part 1
stagedFiles=$(git diff --staged --name-only)

# Part 2
echo "Running spotlessApply. Formatting code..."
cd $PROJECT_ROOT && ./gradlew spotlessApply

if [ $? -ne 0 ]; then
    echo "Spotless apply failed!"
    exit 1
fi

# Part 3
for file in $stagedFiles; do
  if test -f "$file"; then
    git add $file
  fi
done

# 최초 적용시 ./.git/hooks/pre-commit 파일을 생성하고 위의 내용을 복사합니다.
# 스크립트가 변경되면 ./gradlew compileJava를 실행합니다.